import type { LucideIcon } from "lucide-react";
import {
  BarChart3Icon,
  BookOpenIcon,
  BotIcon,
  BriefcaseIcon,
  CalendarIcon,
  CircleDollarSignIcon,
  ClockIcon,
  CloudIcon,
  CpuIcon,
  DumbbellIcon,
  Flower2Icon,
  GlobeIcon,
  GraduationCapIcon,
  HeartIcon,
  HotelIcon,
  LayoutIcon,
  MailIcon,
  MapPinIcon,
  MessageCircleIcon,
  PackageIcon,
  PawPrintIcon,
  PlugIcon,
  QrCodeIcon,
  RefreshCwIcon,
  ScissorsIcon,
  ShieldIcon,
  ShirtIcon,
  SlidersHorizontalIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SparklesIcon,
  StethoscopeIcon,
  StoreIcon,
  TrophyIcon,
  UsersIcon,
  UtensilsCrossedIcon,
  WalletIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";

import type { CatalogIconName } from "@/lib/local-catalog/types";

export const CATALOG_ICONS: Record<CatalogIconName, LucideIcon> = {
  scissors: ScissorsIcon,
  sparkles: SparklesIcon,
  flower: Flower2Icon,
  paw: PawPrintIcon,
  stethoscope: StethoscopeIcon,
  dumbbell: DumbbellIcon,
  trophy: TrophyIcon,
  utensils: UtensilsCrossedIcon,
  shirt: ShirtIcon,
  "shopping-bag": ShoppingBagIcon,
  wrench: WrenchIcon,
  hotel: HotelIcon,
  graduation: GraduationCapIcon,
  briefcase: BriefcaseIcon,
  store: StoreIcon,
  calendar: CalendarIcon,
  message: MessageCircleIcon,
  users: UsersIcon,
  refresh: RefreshCwIcon,
  package: PackageIcon,
  dollar: CircleDollarSignIcon,
  cart: ShoppingCartIcon,
  globe: GlobeIcon,
  bot: BotIcon,
  chart: BarChart3Icon,
  heart: HeartIcon,
  zap: ZapIcon,
  layout: LayoutIcon,
  book: BookOpenIcon,
  plug: PlugIcon,
  "map-pin": MapPinIcon,
  cpu: CpuIcon,
  cloud: CloudIcon,
  shield: ShieldIcon,
  mail: MailIcon,
  qr: QrCodeIcon,
  clock: ClockIcon,
  wallet: WalletIcon,
  sliders: SlidersHorizontalIcon,
};

export function CatalogIcon({
  name,
  className,
}: {
  name: CatalogIconName;
  className?: string;
}) {
  const Icon = CATALOG_ICONS[name];
  return <Icon className={className} aria-hidden />;
}
